### ISSUE TITLE
Daemon

### ISSUE THREAD

**Issue by marco-hoyer** [skymill/aws-ec2-assign-elastic-ip#11]
Hi,

I'm currently thinking of this tool as a daemon starting and stopping with the instance to handle elastic ip's. This would obsolete any execution of this in the user-data section. Would you be willing to accept a pull-request for this? Maybe with a sysconfig switch to define if it should start as daemon or not?!

greets

**Comment by sebdah** [comment]
It would be great to add daemon support. However, I assume that you mean offering both command line execution (like today) and daemon mode, right?

A pull request would be welcome and considered.

**Comment by marco-hoyer** [comment]
Ok, so I will do so and send a pull request. Thanks.
