### ISSUE TITLE
Manage network interface only EIP

### ISSUE THREAD

**Issue by gblachonupg** [skymill/aws-ec2-assign-elastic-ip#18]
Hello,

When we create a NAT Gateway for exemple, the EIP associated to it only has a network interface id, no instance id. 

This result that the command try to allocate this EIP to my instance but get a 400 bad request because EIP already associated to NAT gateway. 

We should modify the _get_unassociated_address() to manage it because today, it only check if EIP as instance ID

Thanks !

**Comment by rauberdaniel** [comment]
I guess #17 would fix this.

**Comment by sebdah** [comment]
This should be fixed in the current release.
